import "./globals.css";
import { Inter } from "next/font/google";
import Wallet from "@/components/Wallet";
import Navbar from "@/components/Navbar";
import Landing from "@/components/Landing";


export const metadata = {
  title: "Nft_marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div >
        <Navbar />
        {children}
       <Landing/>
       
      </div>
     
    </html>
  );
}
