import "./globals.css";
import { Inter } from "next/font/google";
import Wallet from "@/components/Wallet";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nft_marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <div>Hi from layout</div>

      <Wallet />
    </html>
  );
}
